name: Deploy Ghost Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip theme
        run: zip -r theme.zip .

      - name: Upload theme to Ghost
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: |
          curl -X POST "${{ env.GHOST_ADMIN_API_URL }}/themes/upload" \
            -H "Authorization: Ghost ${{ env.GHOST_ADMIN_API_KEY }}" \
            -F "file=@theme.zip"
