name: Sync Ghost Content

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests PyGithub

      - name: Run sync script
        env:
          GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
          GHOST_API_KEY: ${{ secrets.GHOST_API_KEY }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python sync_script.py
